bparlor/routes/web.php
<?php

use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ContactController;
use App\Http\Controllers\Admin\CopyrightController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\PromoController;
use App\Http\Controllers\Admin\TableController;
use App\Http\Controllers\Admin\ReservationController;
use App\Http\Controllers\Admin\ServiceController;
use App\Http\Controllers\Admin\TitleController;
use App\Http\Controllers\Frontend\GalleryController as FrontendGalleryController;
use App\Http\Controllers\Frontend\ContactController as FrontendContactController;
use App\Http\Controllers\Frontend\CategoryController as FrontendCategoryController;
use App\Http\Controllers\Frontend\MenuController as FrontendMenuController;
use App\Http\Controllers\Frontend\ReservationController as FrontendReservationController;
use App\Http\Controllers\Frontend\ServiceController as FrontendServiceController;
use App\Http\Controllers\Frontend\AboutController as FrontendAboutController;
use App\Http\Controllers\Frontend\CopyrightController as FrontendCopyrightController;
use App\Http\Controllers\Frontend\PromoController as FrontendPromoController;
use App\Http\Controllers\Frontend\TitleController as FrontendTitleController;
use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('welcome');
});


Route::get('/galleries', [FrontendGalleryController::class, 'index'])->name('galleries.index');
Route::get('/contacts', [FrontendContactController::class, 'index'])->name('contacts.index');
Route::get('/abouts', [FrontendAboutController::class, 'index'])->name('abouts.index');
Route::get('/titles', [FrontendTitleController::class, 'index'])->name('titles.index');
Route::get('/promos', [FrontendPromoController::class, 'index'])->name('promos.index');
Route::get('/copyrights', [FrontendCopyrightController::class, 'index'])->name('copyrights.index');
Route::get('/services', [FrontendServiceController::class, 'index'])->name('services.index');
Route::get('/categories', [FrontendCategoryController::class, 'index'])->name('categories.index');
Route::get('/categories{category}', [FrontendCategoryController::class, 'index'])->name('categories.show');
Route::get('/menus', [FrontendMenuController::class, 'index'])->name('menus.index');
Route::get('/reservations/step-one', [FrontendReservationController::class, 'stepOne'])->name('reservations.step.one');
Route::post('/reservations/step-one', [FrontendReservationController::class, 'storeStepOne'])->name('reservations.store.step.one');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::middleware(['auth','admin'])->name('admin.')->prefix('admin')->group(function() {
    Route::get('/', [AdminController::class, 'index'])->name('index');
    Route::resource('/categories', CategoryController::class);
    Route::resource('/menus', MenuController::class);
    Route::resource('/tables', TableController::class);
    Route::resource('/reservations', ReservationController::class);
    Route::resource('/services', ServiceController::class);
    Route::resource('/customers', CustomerController::class);
    Route::resource('/titles', TitleController::class);
    Route::resource('/abouts', AboutController::class);
    Route::resource('/promos', PromoController::class);
    Route::resource('/copyrights', CopyrightController::class);
    Route::resource('/galleries', GalleryController::class);
    Route::resource('/contacts', ContactController::class);
    Route::resource('/users', AdminController::class);
});

require __DIR__. '/auth.php';

bparlor/app/Models/About.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class About extends Model
{
    use HasFactory;

    protected $fillable = ['image','about_us'];

}

bparlor/app/Http/Controllers/Admin/AboutController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\AboutStoreRequest;
use App\Models\About;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class AboutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $abouts = About::all();
        return view('admin.abouts.index', compact('abouts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AboutStoreRequest $request)
    {
        $image = $request->file('image')->store('public/abouts');

        About::create([
            'image' => $image,
            'about_us' => $request->about_us
    
        ]);

        return to_route('admin.abouts.index')->with('success', 'Created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(About $about)
    {
        return view('admin.abouts.edit', compact('about'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AboutStoreRequest $request, About $about)
    {
        $request->validate([
            'about_us' => 'required',
        ]);
        
        $image = $about->image;
        if($request->hasFile('image')){
            Storage::delete($about->image);
            $image = $request->file('image')->store('public/abouts');
        }

        $about->update([
            'image' => $image,
            'about_us' => $request->about_us,
           
        ]);

        return to_route('admin.abouts.index')->with('success', 'Updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

bparlor/app/Http/Controllers/Frontend/AboutController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\About;
use Illuminate\Http\Request;

class AboutController extends Controller
{
    public function index()
    {
        $abouts = About::all();
        return view('abouts.index', compact('abouts'));
    }
}

bparlor/app/View/Components/AdminLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AdminLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.admin');
    }
}

bparlor/resources/views/admin/abouts/edit.blade.php
<x-admin-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">   
            <div class="flex m-2 p-2">
                <a href="{{ route('admin.abouts.index') }}" 
                class="px-4 py-2 bg-slate-500 hover:bg-slate-700 rounded-lg text-white">About Index</a>
            </div>
            <div class="m-2 p-2 bg-slate-100 rounded">
                <div class="space-y-8 divide-y divide-gray-200 w-1/2 mt-10">
                    <form method="POST" action="{{ route('admin.abouts.update', $about->id) }}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="sm:col-span-6">

                        <label for="image" class="block text-sm font-medium text-gray-700"> Image </label>
                        <div>
                            <img class="w-32 h-32" src="{{ Storage::url($about->image) }}">
                        </div>
                        <div class="mt-1">
                            <input type="file" id="image" name="image" 
                            class="block w-full appearance-none bg-white border border-gray-400 rounded-md py-2 px-3 text-base leading-normal transition duration-150 ease-in-out sm:text-sm sm:leading-
                            @error('image') border-red-400 @enderror" />
                        </div>

                            <label for="about_us" class="block text-sm font-medium text-gray-700"> About Us </label>
                                <div class="mt-1">
                                    <textarea id="about_us" name="about_us" cols="60" rows="10"
                                        class="block w-full transition-none bg-white border border-gray-400 rounded-md py-2 px-3 text-base leading-normal transition duration-150 ease-in-out sm:text-sm sm:leading-5 
                                        @error('about_us') border-red-400 @enderror">
                                        {{ $about->about_us }}</textarea>
                                </div>
                                @error('about_us')
                                <div class="text-sm text-red-400">{{ $message }}</div>
                                @enderror

                        
                        <div class="mt-5 p-2">
                            <button type="submit" 
                                class="px-4 py-2 bg-blue-500 hover:bg-blue-600 rounded-lg text-white">Update</button>
                        </div>
                    </form>
                </div>

            </div>
            
        </div>  
    </div>
</x-admin-layout>

bparlor/resources/views/admin/abouts/index.blade.php
<x-admin-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
<div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left text-gray-500 dark:bg-slate-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-4 py-4">
                   Image
                </th>
                <th scope="col" class="px-4 py-4">
                    About Us
                </th>
               
                <th scope="col" class="px-4 py-4">
                    Action
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach ($abouts as $about)
            <tr class="bg-white text-gray-700 tracking-wide border-b dark:bg-gray-800 dark:border-gray-700">
                
                <td class="font-semibold px-2 py-4">
                    <img src=" {{ Storage::url($about->image) }}" class="w-16 h-16 rounded">
                </td>
                <td class="font-normal px-4 py-6">
                    {{ $about->about_us }}
                </td>
    
                <td class="px-4 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap dark:text-white">
                    <div class="flex space-x-2">
                        <a href="{{ route('admin.abouts.edit', $about->id) }}" 
                            class="px-4 py-2 bg-slate-500 hover:bg-slate-700 rounded-lg text-white">Edit</a>
                    </div>
                    
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    </div>
    
    </div>
    </div>
</x-admin-layout>